In [2]:
# import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.12.0


In [3]:
# Creating tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
# Check the number of fimesnions of a tensor (ndim  stands fpr number of dimesnions)
scalar.ndim

0

In [5]:

# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [6]:
# Check dimension of vector
vector.ndim

1

In [7]:
# Create a matrix has more than 1 dimension
matrix = tf.constant([[10,7],
                      [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [8]:
# Check the dimension of matrix
matrix.ndim

2

In [9]:
# Create another matrix
another_matrix = tf.constant([[10.,7.],
                              [3.,2.],
                              [8.,9.]], dtype = tf.float16) # specify the data type with dtype parameter
# default dtype is int
another_matrix;

In [10]:
# What is the number of dimensions of another_matrix
another_matrix.ndim

2

In [11]:
# Let's create a tensor
tensor = tf.constant([[[1,2,3],[4,5,6],[7,8,9]]])
tensor

<tf.Tensor: shape=(1, 3, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]], dtype=int32)>

What we have created so far :  

*    Scalar : a single number
*    Vector : a number with direction (e.g. wind speed and direction)
*   Matrix : a 2-dimensional array of numbers
*   Tensor : an n-dimensional array of number n can be any number (positive)







Creatinf tensors with tf.Variable

In [12]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [13]:
# Create the same tensor with tf.Variable as above tf.constant
changable_tensor = tf.Variable([10,7])
unchangable_tensor = tf.constant([10,7])
changable_tensor, unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [14]:
# let's try to change one of elements in our changable tensor
#changable_tensor[0] = 7

In [15]:
# How about try .assign()
changable_tensor[0].assign(7)
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [16]:
# let's try to change one of elements in our unchangable tensor
#unchangable_tensor[0] = 7

In [17]:
# How about try .assign()
#unchangable_tensor[0].assign(7)
#unchangable_tensor

In [18]:
# the we learned that the tensor that is created with tf.constant can not be changed but the tensor that is
# produced with tf.Variable can be changed via assign not with "="

**Creating random tensors**

Random tensors are tensors of some arbitrary size which contain random numbers.

In [19]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_2 = random_2.normal(shape=(3,2))

# Are they equal
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

**Suffling the tensors**

shuffle order of the tensors

In [20]:
# shuffle a tensor (valuable for when you want to shuffle your data so the inherent  order does not effect learning )
not_shuffled = tf.constant([[10,7],[3,4],[2,5]])
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [21]:
# shuffle our non_shuffled tensor
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [22]:
# shuffle our non_shuffled tensor
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [10,  7],
       [ 2,  5]], dtype=int32)>

In [23]:
# shuffle our non_shuffled tensor
tf.random.shuffle(not_shuffled,seed = 42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [24]:
# shuffle our non_shuffled tensor
tf.random.set_seed(42)                              # global seed
tf.random.shuffle(not_shuffled,seed = 42)           # not global level seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [25]:
tf.random.shuffle(not_shuffled, seed = 42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]], dtype=int32)>

**Other ways to create tensors**

In [26]:
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [27]:
tf.zeros(shape = (3,4)) # same as tf.zeros([3,4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

Turn numpy arrays into tensors main difference is that tensors can be run on a GPU (much faster for numerical computing)

In [28]:
# You can also turn numpy arrays into tensors
import numpy as np
numpy_A = np.arange(1,25,dtype = np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [29]:
# convert numpy array into tensors
array = tf.constant(numpy_A,shape = (2,3,4))
array1 = tf.constant(numpy_A)
array,array1

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

**Getting information from tensors**

When dealing with tensors you probably want to be aware of the followning attributes:

*    Shape
*    Rank
*    Axis or Dimension
*    Size







In [30]:
# create a rank 4 tensor(we want four dimension)
rank_4_tensor = tf.zeros(shape = (2,3,4,5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [31]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [32]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [33]:
# Get various attributes of our tensor
print("Data type of every element :",rank_4_tensor.dtype)
print("Number of dimensions (rank) :",rank_4_tensor.ndim)
print("Shape of tensor :",rank_4_tensor.shape)
print("Elements along the 0 axis :",rank_4_tensor.shape[0])
print("Elements along the last axis :",rank_4_tensor.shape[-1])
print("Total number of elements :",tf.size(rank_4_tensor))
print("Total number of elements :",tf.size(rank_4_tensor).numpy())

Data type of every element : <dtype: 'float32'>
Number of dimensions (rank) : 4
Shape of tensor : (2, 3, 4, 5)
Elements along the 0 axis : 2
Elements along the last axis : 5
Total number of elements : tf.Tensor(120, shape=(), dtype=int32)
Total number of elements : 120


**Indexing tensors**


---


Tensors can be indexed just like Python Lists

In [34]:
some_list = [1,2,3,4]
some_list[:2]

[1, 2]

In [35]:
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [36]:
# Get the first element from each dimension from each index except for the final one
rank_4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [37]:
# Create a rank 2 tensor(2 dimensions)
rank2_tensor = tf.constant([[10,7],
                            [3,4]])
rank2_tensor.shape, rank2_tensor.ndim,

(TensorShape([2, 2]), 2)

In [38]:
# get the last item of each of row of our rank 2 tensor
rank2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [39]:
# Add in extra dimesnison to our rank 2 tensor
rank3_tensor = rank2_tensor[..., tf.newaxis]
rank3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [40]:
# alternative to tf.newaxis
tf.expand_dims(rank2_tensor, axis = -1) # -1 means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [41]:
tf.expand_dims(rank2_tensor, axis = 0)  # add to beginning

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

**Manipulating tensors (operations on tensors)**

---



---



**Basic operations**

*   + , - , /, *



In [42]:
tensor = tf. constant([[10,7],
                       [3,4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [43]:
tensor*10


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [44]:
# We can use tensorflow builtin functions
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

**Matrix Multiplication**

1.   In machine learning matrix multiplication is one of the most important key points



In [45]:
# Matrix multiplication
print(tensor)
tf.matmul(tensor,tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [46]:
tensor*tensor # elementwise multiplication

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [47]:
# Matix multiplication with python operator @
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [48]:
tensor.shape

TensorShape([2, 2])

In [49]:
# Create tensor with different size (3,2)
x = tf.constant([[1,2],
                 [3,4],
                 [5,6]])

In [50]:
y = tf.constant([[7,8],
                 [9,10],
                 [11,12]])

In [51]:
# Try to multiply them we will get error becasue their dimensions are not suitable

In [52]:
# Let's chane the shape of y
y=tf.reshape(y,shape = (2,3))

In [53]:
x @ y

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [54]:
tf.matmul(x,y)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [55]:
tf.transpose(x)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]], dtype=int32)>

In [56]:
# Try to matrix multiplication with transpose
x @ tf.transpose(x)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 5, 11, 17],
       [11, 25, 39],
       [17, 39, 61]], dtype=int32)>

The dot product

In [57]:
y=tf.reshape(y,shape = (3,2))

In [58]:
x,y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [59]:
# Perform the dot product on x and y (requires x or y to be transposed)
tf.tensordot(tf.transpose(x),y,axes = 1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [60]:
tf.tensordot(tf.transpose(x),y,axes = 2)

<tf.Tensor: shape=(), dtype=int32, numpy=212>

In [61]:
# Perform matrix multiplication between x and y (transposed)
tf.matmul(x,tf.transpose(y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [62]:
# Perform matrix multiplication between x and y (reshaped)
tf.matmul(x,tf.reshape(y ,shape = (2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [63]:
# Check the values of y, reshape y and transpose y
print("Normal y : ",y)
print("Y reshaped  : ",tf.reshape(y, shape = (2,3)))
print("Y transposed : ",tf.transpose(y))

Normal y :  tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32)
Y reshaped  :  tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32)
Y transposed :  tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


**Changing the data type of a tensor**

In [64]:
# Create a new tensor with default datatype (float32)
B = tf.constant([1.7,7.4])
B.dtype


tf.float32

In [65]:
C = tf.constant([1,7])
C.dtype

tf.int32

In [66]:
# Change from float32 to float16 (reduced precision)
D = tf.cast(B,dtype = tf.float16)
D

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

In [67]:
B,D

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.4], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>)

In [68]:
# Changing dtype enable hardware accelerometer to run faster approximately two times

In [69]:
# Change from int32 to float32
E = tf.cast(C, dtype = tf.float32)
C,E

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 7.], dtype=float32)>)

**Aggregating Tensors**

*   Aggregation tensors = condensing them from multiple values down to a smaller amount of values
*  



In [70]:
# Get the absolute values
D = tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [71]:
# Get absoulte value
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

# Let's  go through the following from of aggregation:

*   get minimum
*   get maximum
1.   get sum
2.   get mean





In [72]:
# Create a random tensor with values between 0 and 100 of size 50
tensor = tf.constant(np.random.randint(0,100,size = 50))
tensor

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([67,  7, 27, 90, 41,  4, 57, 41, 26, 71, 29, 87, 54,  6, 65, 25, 16,
       13, 17, 49, 40, 52, 60, 52, 36, 40, 38,  2, 99, 61, 22, 20, 83, 91,
       97, 44, 19, 89, 21, 28, 74, 90,  6, 71, 58, 31, 35, 66,  0, 74])>

In [73]:
tf.size(tensor), tensor.shape, tensor.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [74]:
# Find the min
tf.reduce_min(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [75]:
# Find the max
tf.reduce_max(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [76]:
# find the mean
tf.reduce_mean(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=45>

In [77]:
# find the sum
tf.reduce_sum(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=2291>

In [78]:
# find the variance of our tensor
# tf.reduce_variance(tensır) will not work

In [79]:
# To find the varience of our tensor, we need access to tensorflow_probability
import tensorflow_probability as tfp
tfp.stats.variance(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=790>

In [80]:
# Find the standart deviation
tf.math.reduce_std(tf.cast(tensor,dtype = tf.float32))
# do not forget this usage

<tf.Tensor: shape=(), dtype=float32, numpy=28.099602>

In [81]:
# another way of finding variance
tf.math.reduce_variance(tf.cast(tensor, dtype = tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=789.5876>

Find the positional maximum and minimum

In [82]:
# Create a new tensor for finding positional minimum and maximum
tf.random.set_seed(42)
f = tf.random.uniform(shape = [50])
f

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [83]:
# Find the positional maximum
tf.argmax(f)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [84]:
# Index on our largest value position
f[tf.argmax(f)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [85]:
# Find the max
tf.reduce_max(f)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [86]:
# Check for equality
tf.reduce_max(f) == f[tf.argmax(f)]

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [87]:
# Find the positional minimum
tf.argmin(f)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [88]:
# Index on our smallest value position
f[tf.argmin(f)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

**Squeezing a tensor (removing all single dimensions)**

In [89]:
# Create a tensor to get started
tf.random.set_seed(42)
g = tf.constant(tf.random.uniform(shape = [50]), shape = (1,1,1,1,50))
g


<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [90]:
g.shape

TensorShape([1, 1, 1, 1, 50])

In [91]:
g_squeezed = tf.squeeze(g)
g_squeezed, g_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

**One - hot encoding tensors**

In [92]:
# Create a list of indices
some_list = [0,1,2,3] # could be red, green , blue, purple

# One hot encode our list indices
tf.one_hot(some_list, depth = 4)
# we need to give depth property with the length of the tensor

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [93]:
# Specify custom values for one hot encoding
tf.one_hot(some_list, depth = 4, on_value = 'I love deep learning', off_value = 'I also like to dance')

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'I love deep learning', b'I also like to dance',
        b'I also like to dance', b'I also like to dance'],
       [b'I also like to dance', b'I love deep learning',
        b'I also like to dance', b'I also like to dance'],
       [b'I also like to dance', b'I also like to dance',
        b'I love deep learning', b'I also like to dance'],
       [b'I also like to dance', b'I also like to dance',
        b'I also like to dance', b'I love deep learning']], dtype=object)>

**Mathematical operations**

*   Squaring
*   Log
*   Square root





In [94]:
# Create a new tensor
h = tf.range(1,10)
h

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [95]:
# square it
tf.square(h)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [96]:
# square root
tf.math.sqrt(tf.cast(h,dtype = tf.float32)) # do not forget this method requires non int type

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.2360678, 2.4494896,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [97]:
# find the log
tf.math.log(tf.cast(h,dtype = tf.float32)) # same as above

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

**Tensor and Numpy Compability**

Tensorflow interacts beautifully with numpy arrays


In [98]:
# Create a tensor directly from a numpy array
j = tf.constant(np.array([3.,7.,10.]))
j

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [99]:
# Convert out tensor back to Numpy array
np.array(j), type(np.array(j))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [100]:
# Convert tensor j to a Numpy array
j.numpy(), type(j.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [101]:
# The default types of each are slightly different
numpy_j = tf.constant(np.array([3.,7.,10.]))
tensor_j = tf.constant([3.,7.,10.])

In [102]:
# Check the  datatypes of each
numpy_j.dtype, tensor_j.dtype

(tf.float64, tf.float32)

**IMPORTANT NOTE**
Main difference between numpy and tensor is that tensor can run faster via GPU and TPU

**Finding access to GPUs**

In [103]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [104]:
# We can pass parameter to know which hardware is used
tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [105]:
tf.config.list_physical_devices("TPU")

[]

In [106]:
tf.config.list_physical_devices("CPU")

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [107]:
# gettting information about hardware accelerator
! nvidia-smi

Tue Aug 29 08:35:25 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   60C    P0    28W /  70W |    389MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

**NOTE : **
If you have access to a CUDA-enabled GPU, TensorFlow will automatically use it whenever possible